# Generated by Django 4.2.6 on 2024-02-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("dob", models.DateField()),
                ("address", models.TextField()),
                ("phone", models.CharField(max_length=15)),
                ("experience", models.FloatField()),
                ("designation", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="SalaryPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("YearsExperience", models.FloatField()),
                ("Salary", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
